from pydantic import BaseModel, Field
from typing import List

from schemas.market_schema import MarketOutput
from schemas.competitor_schema import CompetitorOutput
from schemas.trend_schema import TrendOutput


class ReportInput(BaseModel):
    market_analysis: MarketOutput = Field(
        description="Output generated by the Market Agent."
    )

    competitor_analysis: CompetitorOutput = Field(
        description="Output generated by the Competitor Agent."
    )

    trend_analysis: TrendOutput = Field(
        description="Output generated by the Trend Agent."
    )


class ReportOutput(BaseModel):
    title: str = Field(
        description="Title of the report."
    )

    executive_summary: str = Field(
        description="Executive summary of the report."
    )

    market_overview: str = Field(
        description="Summary of the market analysis."
    )

    competitor_analysis: str = Field(
        description="Summary of competitor analysis."
    )

    trend_analysis: str = Field(
        description="Summary of market trends."
    )

    key_opportunities: List[str] = Field(
        description="Key business opportunities."
    )

    risks: List[str] = Field(
        description="Potential business risks."
    )

    recommendations: List[str] = Field(
        description="Strategic recommendations."
    )

    conclusion: str = Field(
        description="Final conclusion."
    )